func forReplace(codeMsg):
  codeMsg = codeMsg.change(/for\s(.+?)=(.+?)\sto\s(.+?)\:/g, (match, p1, p2, p3) => `for (let ${p1} = ${p2}; ${p1} < ${p3}; ${p1}++) {`);
  codeMsg = codeMsg.change(/for\s(.+?)\sof\s(.+?)\:/g, (match, p1, p2) => `for (${p1} of ${p2}) {`)
  codeMsg = codeMsg.change(/for\s(.+?)\sin\s(.+?)\:/g, (match, p1, p2) => `for (${p1} in ${p2}) {`)
  return codeMsg
end

module.exports = { forReplace }